# Nom de votre Github Actions
name: CI/CD APP JAVA

# Triggers ou déclencheurs
# Lors d'un push sur la branch main
on:
  push:
    branches: [ "main" ]

# Déclenchement des jobs lors d'un push
jobs:

  # Etape 1: se connecte en ssh et créer un répertoire
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
  
    steps:
  
      # Action 1
    - name: Create folder on remote VM
      uses: appleboy/ssh-action@v1.0.3

      # Rajouter les secrets dans settings => secrets and variables
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        
        #script à exécuter
        script: mkdir -p /opt/applications/haltereit
  
  # Etape 2: build the project
  build:
  
    # Environnement exécution
    runs-on: ubuntu-latest
    
    # si action create-folder reussi alors execute la copie
    needs: create-folder
    
    steps:
  
      # Action 1
    - name: Checkout du code
      uses: actions/checkout@v4
  
      # Action 2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
  
      # Action 3 => Build du projet avec Maven    
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml

      # Rename jar
    - name: Rename jar
      run: mv target/*.jar target/imc.jar

      # Copy jar on remote VM
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7

      # Rajouter les secrets dans settings => secrets and variables
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "target/imc.jar"
        target: /opt/applications/haltereit

  # Etape 3: run jar
  run-jar:
    name: run-jar
    runs-on: ubuntu-latest
  
     # si action build reussi alors execute le jar
    needs: build

    steps:
  
      # Action 1
    - name: Execute le jar
      uses: appleboy/ssh-action@v1.0.3

      # Rajouter les secrets dans settings => secrets and variables
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        
        #script à exécuter
        #script: java -jar /opt/applications/haltereit/target/imc.jar
        script: whoami